[package]
name = "io2"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
io-uring = "0.6.4"
libc = "0.2"
nohash-hasher = "0.2.0"
pin-project-lite = "0.2"
log = "0.4"
hashbrown = { version = "0.14", default-features = false, features = ["nightly"] }
